/**
 * Supported types of AST nodes generated by the Markdown parser.
 */
const enum MDNodeType {
    // Inline Node Types
    text = "md-text",
    bold = "md-bold",
    italic = "md-italic",
    link = "md-link",
    inlineCode = "md-inline-code",
    inlineMath = "md-inline-math",
    superScript = "md-sup",
    subScript = "md-sub",
    lineBreak = "md-br",

    // Block Node Types
    heading = "md-heading",
    paragraph = "md-paragraph",
    blockquote = "md-blockquote",
    list = "md-list",
    listItem = "md-list-item",
    blockCode = "md-block-code",
    blockMath = "md-block-math",
    horizontalRule = "md-hr",
}

/**
 * Supported severity levels for blockquotes.
 */
const enum MDBlockquoteType {
    // Highlight
    default = "md-blockquote-default",

    // Severity based
    info = "md-blockquote-info",
    success = "md-blockquote-success",
    warn = "md-blockquote-warn",
    error = "md-blockquote-error",
}

/**
 * Ordering types for list elements.
 */
const enum MDListOrderingType {
    // Unordered lists
    hyphen = "md-list-unordered-hyphen",
    plus = "md-list-unordered-plus",
    asterisk = "md-list-unordered-asterisk",

    // Ordered lists
    oneTwoThree = "md-list-ordered-123",
    abc = "md-list-ordered-abc",
    ABC = "md-list-ordered-ABC",
    ivx = "md-list-ordered-ivx",
    IVX = "md-list-ordered-IVX",
}

/**
 * Base node interface.
 */
interface _MDNode {
    type: MDNodeType;
}

// -----------------------------------------------------------------------------
// Inline Nodes

/**
 * Represents raw literal text.
 */
interface TextNode extends _MDNode {
    type: MDNodeType.text;
    content: string;
}

/**
 * Represents bold formatted inline text.
 */
interface BoldNode extends _MDNode {
    type: MDNodeType.bold;
    contents: InlineNode[];
}

/**
 * Represents italic formatted inline text.
 */
interface ItalicNode extends _MDNode {
    type: MDNodeType.italic;
    contents: InlineNode[];
}

/**
 * Represents an inline hyperlink.
 */
interface LinkNode extends _MDNode {
    type: MDNodeType.link;
    href: string;
    contents: InlineNode[];
}

/**
 * Represents inline monospace code text.
 */
interface InlineCodeNode extends _MDNode {
    type: MDNodeType.inlineCode;
    content: string;
}

/**
 * Represents inline mathematical notation.
 */
interface InlineMathNode extends _MDNode {
    type: MDNodeType.inlineMath;
    content: string;
}

/**
 * Represents superscript text structure.
 */
interface SuperScriptNode extends _MDNode {
    type: MDNodeType.superScript;
    contents: InlineNode[];
}

/**
 * Represents subscript text structure.
 */
interface SubScriptNode extends _MDNode {
    type: MDNodeType.subScript;
    contents: InlineNode[];
}

/**
 * Represents a forced line break within inline text.
 */
interface BrNode extends _MDNode {
    type: MDNodeType.lineBreak;
}

type InlineNode =
    | TextNode
    | BoldNode
    | ItalicNode
    | LinkNode
    | InlineCodeNode
    | InlineMathNode
    | SuperScriptNode
    | SubScriptNode
    | BrNode;

// -----------------------------------------------------------------------------
// Block Nodes

/**
 * Represents a structural heading node.
 */
interface HeadingNode extends _MDNode {
    type: MDNodeType.heading;
    level: 1 | 2 | 3 | 4 | 5 | 6;
    children: InlineNode[];
}

/**
 * Represents a paragraph of text.
 */
interface ParagraphNode extends _MDNode {
    type: MDNodeType.paragraph;
    children: InlineNode[];
}

/**
 * Represents a blockquote section, with an optional severity level.
 */
interface BlockquoteNode extends _MDNode {
    type: MDNodeType.blockquote;
    severity: MDBlockquoteType;
    children: BlockNode[];
}

/**
 * Represents an ordered or unordered list container.
 */
interface ListNode extends _MDNode {
    type: MDNodeType.list;
    ordering: MDListOrderingType;
    children: ListItemNode[];
}

/**
 * Represents a list item within a list.
 */
interface ListItemNode extends _MDNode {
    type: MDNodeType.listItem;
    contents: InlineNode[];
}

/**
 * Represents a multi-line syntax-highlighted code block.
 */
interface BlockCodeNode extends _MDNode {
    type: MDNodeType.blockCode;
    lang?: string;
    content: string;
}

/**
 * Represents a multi-line mathematical block equation.
 */
interface BlockMathNode extends _MDNode {
    type: MDNodeType.blockMath;
    content: string;
}

/**
 * Represents a thematic horizontal rule divider.
 */
interface HrNode extends _MDNode {
    type: MDNodeType.horizontalRule;
}

type BlockNode =
    | HeadingNode
    | ParagraphNode
    | BlockquoteNode
    | ListNode
    | ListItemNode
    | BlockCodeNode
    | BlockMathNode
    | HrNode;

// -----------------------------------------------------------------------------
// Metadata

/**
 * Extracted frontmatter/publication metadata of the parsed document.
 */
interface MDMetadata {
    publication?: {
        author: string;
        published: string;
        conceived: string;
    };
}

/**
 * Structure returned by the Markdown parser.
 */
interface MDParseResult {
    children: BlockNode[];
    metadata: MDMetadata;
}

// -----------------------------------------------------------------------------
// Exports

export type {
    InlineNode,
    BlockNode,
    TextNode,
    BoldNode,
    ItalicNode,
    LinkNode,
    InlineCodeNode,
    InlineMathNode,
    SuperScriptNode,
    SubScriptNode,
    BrNode,
    HeadingNode,
    ParagraphNode,
    BlockquoteNode,
    ListNode,
    ListItemNode,
    BlockCodeNode,
    BlockMathNode,
    HrNode,
    MDMetadata,
    MDParseResult,
};

export {
    MDNodeType,
    MDBlockquoteType,
    MDListOrderingType,
};
