/**
 * @fileoverview Style Dictionary build script for biocircuit.
 *
 * Compiles W3C DTCG tokens (primitives and semantics) into CSS custom properties
 * with the `--cwbwbc` prefix for both Light and Dark themes.
 *
 * Output targets:
 * - dist/css/primitives.css   : Base 6x9 primitive color scales
 * - dist/css/theme-light.css  : Light theme substrates and cybernetic channels
 * - dist/css/theme-dark.css   : Dark theme substrates and cybernetic channels
 * - dist/css/index.css        : Combined entrypoint with media query and data-theme selectors
 */

import StyleDictionary from 'style-dictionary';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '..');
const DIST_DIR = path.join(ROOT_DIR, 'dist', 'css');

// POSIX normalized path helper for globs
function toPosix(p: string): string {
    return p.replace(/\\/g, '/');
}

async function build(): Promise<void> {
    if (!fs.existsSync(DIST_DIR)) {
        fs.mkdirSync(DIST_DIR, { recursive: true });
    }

    const primitivesGlob = toPosix(path.join(ROOT_DIR, 'tokens', 'primitives', '**', '*.json'));
    const lightPath = toPosix(path.join(ROOT_DIR, 'tokens', 'semantics', 'light.json'));
    const darkPath = toPosix(path.join(ROOT_DIR, 'tokens', 'semantics', 'dark.json'));

    // 1. Compile Primitives
    const sdPrimitives = new StyleDictionary({
        source: [primitivesGlob],
        platforms: {
            css: {
                transformGroup: 'css',
                prefix: 'cwbwbc',
                buildPath: 'dist/css/',
                files: [
                    {
                        destination: 'primitives.css',
                        format: 'css/variables',
                        options: {
                            outputReferences: true
                        }
                    }
                ]
            }
        }
    });
    await sdPrimitives.buildAllPlatforms();

    // 2. Compile Light Theme Semantics
    const sdLight = new StyleDictionary({
        source: [primitivesGlob, lightPath],
        platforms: {
            css: {
                transformGroup: 'css',
                prefix: 'cwbwbc',
                buildPath: 'dist/css/',
                files: [
                    {
                        destination: 'theme-light.css',
                        format: 'css/variables',
                        filter: (token) => toPosix(token.filePath ?? '').includes('semantics'),
                        options: {
                            outputReferences: true,
                            selector: ':root, [data-theme="light"]'
                        }
                    }
                ]
            }
        }
    });
    await sdLight.buildAllPlatforms();

    // 3. Compile Dark Theme Semantics
    const sdDark = new StyleDictionary({
        source: [primitivesGlob, darkPath],
        platforms: {
            css: {
                transformGroup: 'css',
                prefix: 'cwbwbc',
                buildPath: 'dist/css/',
                files: [
                    {
                        destination: 'theme-dark.css',
                        format: 'css/variables',
                        filter: (token) => toPosix(token.filePath ?? '').includes('semantics'),
                        options: {
                            outputReferences: true,
                            selector: '[data-theme="dark"]'
                        }
                    }
                ]
            }
        }
    });
    await sdDark.buildAllPlatforms();

    // 4. Create combined entrypoint with dual-theme media-query & data-theme support
    const darkContent = fs.readFileSync(path.join(DIST_DIR, 'theme-dark.css'), 'utf-8');
    const innerVarsMatch = darkContent.match(/\[data-theme="dark"\]\s*\{([\s\S]*?)\}/);
    const darkVars = innerVarsMatch ? innerVarsMatch[1].trim() : '';

    const indexCss = `/**
 * @crabwire/bloatware-biocircuit
 * Design system tokens entrypoint.
 * Auto-generated by Style Dictionary. DO NOT EDIT MANUALLY.
 */

@import './primitives.css';
@import './theme-light.css';
@import './theme-dark.css';

/* Default dark theme activation via system preference when no explicit light theme override */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${darkVars
    .split('\n')
    .map(line => `    ${line.trim()}`)
    .filter(Boolean)
    .join('\n')}
  }
}
`;

    fs.writeFileSync(path.join(DIST_DIR, 'index.css'), indexCss, 'utf-8');
    console.log('Successfully built biocircuit CSS tokens in dist/css/');
}

build().catch((err) => {
    console.error('Failed to build tokens:', err);
    process.exit(1);
});
